### ISSUE TITLE
New And Edit Layout UI Enhancemens

### ISSUE THREAD

**Issue by victorkuldeep** [victorkuldeep/Salesforce_ProjectX#7]
1. Account and Contact on Top with 2 Col Layout
2. Section should have grey background - ** Nice to Have not mandatory, Tech feasibility
3. Web to Case & Category OR On Change filters should be controlled via Mode : Edit/New e.g. Edit should have different filter and new as well.
4. Edit/New Modes can have different different sections. Multi Section - Multi Mode

**Comment by Thejasvi44** [comment]
Case Fields
- Category__c 
- Sub_Category__c
- Product__c

First Conditional display : If Case Status is 'Awaiting External' Information_Requested__c (required) field should be displayed for Both New and Edit Case layouts

Second Conditional Display : If Category field is selected as 'Technical Support' then the Product__c field should be displayed for both Case new and Edit Layouts

Case Origin is Web - Display fields readonly for non-System admins and only for Case Edit layout

case resolution section - Display only on Case Edit Layout 
System Information - Display only on Case Edit Layout
Case Origin is Email - Display two fields Web Name and web Email only for Edit Case Layout
Authentication_Override_Reason__c - to be displayed only on Edit layout and read only

**Comment by victorkuldeep** [comment]
_Requirements are added in feature/Feature-006 with framework and fieldMapper.js need to be configured along with section hides accordingly. Component support is added_
